Name = "Tomlyn"
Language = "C#"
Version = "1.0.0"

EnableNullable = false

Source = [
	"Collections/Iterator.cs",
	"Helpers/DateTimeRFC3339.cs",
	"Helpers/ThrowHelper.cs",
	"Model/ObjectKind.cs",
	"Model/SyntaxTransform.cs",
	"Model/TomlArray.cs",
	"Model/TomlBoolean.cs",
	"Model/TomlDateTime.cs",
	"Model/TomlFloat.cs",
	"Model/TomlInteger.cs",
	"Model/TomlObject.cs",
	"Model/TomlString.cs",
	"Model/TomlTable.cs",
	"Model/TomlTableArray.cs",
	"Model/TomlValue.cs",
	"Parsing/ITokenProvider.cs",
	"Parsing/Lexer.cs",
	"Parsing/LexerState.cs",
	"Parsing/Parser.cs",
	"Parsing/SyntaxTokenValue.cs",
	"Syntax/ArrayItemSyntax.cs",
	"Syntax/ArraySyntax.cs",
	"Syntax/BareKeyOrStringValueSyntax.cs",
	"Syntax/BareKeySyntax.cs",
	"Syntax/BooleanValueSyntax.cs",
	"Syntax/ArrayItemSyntax.cs",
	"Syntax/DateTimeValueSyntax.cs",
	"Syntax/DiagnosticMessage.cs",
	"Syntax/DiagnosticMessageKind.cs",
	"Syntax/DiagnosticsBag.cs",
	"Syntax/DocumentSyntax.cs",
	"Syntax/DottedKeyItemSyntax.cs",
	"Syntax/FloatValueSyntax.cs",
	"Syntax/InlineTableItemSyntax.cs",
	"Syntax/InlineTableSyntax.cs",
	"Syntax/IntegerValueSyntax.cs",
	"Syntax/InvalidSyntaxToken.cs",
	"Syntax/KeySyntax.cs",
	"Syntax/KeyValueSyntax.cs",
	"Syntax/SourceSpan.cs",
	"Syntax/StringValueSyntax.cs",
	"Syntax/SyntaxFactory.cs",
	"Syntax/SyntaxKind.cs",
	"Syntax/SyntaxList.cs",
	"Syntax/SyntaxNode.cs",
	"Syntax/SyntaxNodeBase.cs",
	"Syntax/SyntaxNodeExtensions.cs",
	"Syntax/SyntaxToken.cs",
	"Syntax/SyntaxTrivia.cs",
	"Syntax/SyntaxValidator.cs",
	"Syntax/SyntaxVisitor.cs",
	"Syntax/TableArraySyntax.cs",
	"Syntax/TableSyntax.cs",
	"Syntax/TableSyntaxBase.cs",
	"Syntax/TextPosition.cs",
	"Syntax/TokenKind.cs",
	"Syntax/TokenKindExtensions.cs",
	"Syntax/ValueSyntax.cs",
	"Text/char32.cs",
	"Text/CharacterIterator.cs",
	"Text/CharHelper.cs",
	"Text/CharReaderException.cs",
	"Text/ISourceView.cs",
	"Text/IStringView.cs",
	"Text/StringCharacterIterator.cs",
	"Text/StringCharacterUtf8Iterator.cs",
	"Text/StringSourceView.cs",
	"Text/StringUtf8SourceView.cs",
	"Toml.cs",
	"TomlParserOptions.cs",
]

[Dependencies]
Runtime = [
]